
version: '2'

services:

    openjdk:
        build: ./jdk
        ports:
            - "8182:8182"
        links:
            - postgres

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=tim
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/pg_data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
